DROP TABLE IF EXISTS PLAYERS;
DROP TABLE IF EXISTS USERS;

-- Create a table from the csv
CREATE TABLE PLAYERS AS SELECT * FROM CSVREAD('Player.csv');

CREATE TABLE USERS (
   USERID VARCHAR(36) PRIMARY KEY,
   EMAIL VARCHAR(50) UNIQUE,
   FULLNAME VARCHAR(255) NOT NULL,
   ADDRESS VARCHAR(500),
   AGE INT
);